[package]
name = "mypage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = { version = "0.7.0" }
gloo-timers = "0.2.4"
yew = "0.19.3"
